version: '3'
services:
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - api