version: '3'
services:
  db:
    image: mongo:latest
    ports:
      - 27017:27017

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - 8000:8000
    environment:
      - MONGO_URI=mongodb://db:27017
    depends_on:
      - db

  client:
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api
